Imports quartus.CSDK
Public Class Offsets
    Public Shared m_bDormant = &HED
    Public Shared m_clrRender = &H70
    Public Shared m_dwInGame = &H108
    Public Shared m_nModelIndex = &H254
    Public Shared m_hViewModel = &H32DC
    Public Shared m_iWorldModelIndex = &H3214
    Public Shared m_szArmsModel = &H3907
    Public Shared m_iObserverMode = &H334C

    Public Shared m_bGunGameImmunity = ofs.Read("netvars", "m_bGungameImmunity")
    Public Shared m_bSpotted = ofs.Read("netvars", "m_bSpotted")
    Public Shared m_bSpottedByMask = ofs.Read("netvars", "m_bSpottedByMask")
    Public Shared m_dwBoneMatrix = ofs.Read("netvars", "m_dwBoneMatrix")
    Public Shared m_fFlags = ofs.Read("netvars", "m_fFlags")
    Public Shared m_iItemIDHigh = ofs.Read("netvars", "m_iItemIDHigh")
    Public Shared m_OriginalOwnerXuidHigh = ofs.Read("netvars", "m_OriginalOwnerXuidHigh")
    Public Shared m_OriginalOwnerXuidLow = ofs.Read("netvars", "m_OriginalOwnerXuidLow")
    Public Shared m_nFallbackPaintKit = ofs.Read("netvars", "m_nFallbackPaintKit")
    Public Shared m_nFallbackSeed = ofs.Read("netvars", "m_nFallbackSeed")
    Public Shared m_nFallbackStatTrak = ofs.Read("netvars", "m_nFallbackStatTrak")
    Public Shared m_flFallbackWear = ofs.Read("netvars", "m_flFallbackWear")
    Public Shared m_iAccountID = ofs.Read("netvars", "m_iAccountID")
    Public Shared m_iHealth = ofs.Read("netvars", "m_iHealth")
    Public Shared m_iTeamNum = ofs.Read("netvars", "m_iTeamNum")
    Public Shared m_flFlashDuration = ofs.Read("netvars", "m_flFlashDuration")
    Public Shared m_flFlashMaxAlpha = ofs.Read("netvars", "m_flFlashMaxAlpha")
    Public Shared m_vecOrigin = ofs.Read("netvars", "m_vecOrigin")
    Public Shared m_aimPunchAngle = ofs.Read("netvars", "m_aimPunchAngle")
    Public Shared m_vecViewOffset = ofs.Read("netvars", "m_vecViewOffset")
    Public Shared m_iShotsFired = ofs.Read("netvars", "m_iShotsFired")
    Public Shared m_iCrosshairId = ofs.Read("netvars", "m_iCrosshairId")
    Public Shared m_hActiveWeapon = ofs.Read("netvars", "m_hActiveWeapon")
    Public Shared m_vecVelocity = ofs.Read("netvars", "m_vecVelocity")
    Public Shared m_iItemDefinitionIndex = ofs.Read("netvars", "m_iItemDefinitionIndex")
    Public Shared m_iGlowIndex = ofs.Read("netvars", "m_iGlowIndex")
    Public Shared m_iClip1 = ofs.Read("netvars", "m_iClip1")
    Public Shared m_hMyWeapons = ofs.Read("netvars", "m_hMyWeapons")
    Public Shared m_iCompetitiveWins = ofs.Read("netvars", "m_iCompetitiveWins")
    Public Shared m_iCompetitiveRanking = ofs.Read("netvars", "m_iCompetitiveRanking")
    Public Shared dwLocalPlayer = ofs.Read("signatures", "dwLocalPlayer")
    Public Shared dwEntityList = ofs.Read("signatures", "dwEntityList ")
    Public Shared dwClientState = ofs.Read("signatures", "dwClientState ")
    Public Shared dwForceAttack = ofs.Read("signatures", "dwForceAttack")
    Public Shared dwForceJump = ofs.Read("signatures", "dwForceJump")
    Public Shared dwGlowObjectManager = ofs.Read("signatures", "dwGlowObjectManager")
    Public Shared dwRadarBase = ofs.Read("signatures", "dwRadarBase")
    Public Shared dwViewAngles = ofs.Read("signatures", "dwClientState_ViewAngles")
    Public Shared dwGlobalVars = ofs.Read("signatures", "dwGlobalVars")
    Public Shared dwPlayerResource = ofs.Read("signatures", "dwPlayerResource")
End Class
